# Generated by Django 4.1.2 on 2022-11-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Restaurant'), (2, 'Customer')], default=1),
            preserve_default=False,
        ),
    ]
