# Generated by Django 4.1.2 on 2022-11-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vender',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='vender',
            old_name='user_profile',
            new_name='User_profile',
        ),
        migrations.AlterField(
            model_name='vender',
            name='restaurent_liciense',
            field=models.ImageField(blank=True, upload_to='user/liciense'),
        ),
    ]
