# Generated by Django 4.1.2 on 2022-11-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0002_rename_user_vender_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='restaurent_liciense',
            field=models.ImageField(upload_to='user/liciense'),
        ),
    ]
