# Generated by Django 4.1.2 on 2022-11-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0003_alter_vender_restaurent_liciense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vender',
            old_name='restaurent_liciense',
            new_name='vender_liciense',
        ),
        migrations.RenameField(
            model_name='vender',
            old_name='restaurent_name',
            new_name='vender_name',
        ),
    ]
