# Generated by Django 4.1.2 on 2022-11-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0004_rename_restaurent_liciense_vender_vender_liciense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='vender_liciense',
            field=models.ImageField(blank=True, upload_to='user/liciense'),
        ),
    ]
